### ISSUE TITLE
fix fake backend server

### ISSUE THREAD

**Issue by Adam-Goldman7** [ethcore/eth-node-status-page#104]
got broken in https://github.com/ethcore/eth-node-status-page/commit/022e4dec721f604506cbfa4db12e0f68248f00c9

@tomusdrw got any first glance ideas why?

The fakebackend file does get required and loaded
and the fakeRpc is atttaced to window and have the middlewares

**Comment by tomusdrw** [comment]
`require` might be interpreted by webpack as dynamic import (so it's not included in bundled file)
