### ISSUE TITLE
Make demo functional

### ISSUE THREAD

**Issue by Adam-Goldman7** [ethcore/eth-node-status-page#106]
http://ethcore.github.io/eth-node-status-page/

need to point to an active node

**Comment by tomusdrw** [comment]
And add a link in Readme.md

**Comment by tomusdrw** [comment]
Maybe we can use mocked backend for now?

**Comment by Adam-Goldman7** [comment]
we don't support all functions in mocked backend

**Comment by tomusdrw** [comment]
Yeah, but it would work for now:)

**Comment by Adam-Goldman7** [comment]
resolved by #109
