### ISSUE TITLE
E2E tests are failing with authorization issues

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/eth-node-status-page#137]
Example:
https://travis-ci.org/ethcore/eth-node-status-page/jobs/129500170

```
Sauce Labs Authentication Error.
You used username 'ethcoreHQ' and access key '${SAUCE_ACCESS_KEY}' to authenticate, which are not valid Sauce Labs credentials.
```

**Comment by goldylucks** [comment]
I actually got a [different](https://saucelabs.com/jobs/2f6faf4857dc44db9f51697d730b1498) error now
No active tunnel found for identifier '514.4'

I C u removed the access user from travis.yml and changed the key
that was after it started failing?

**Comment by tomusdrw** [comment]
Yup. Tried to encrypt `SAUCE_ACCESS_KEY` again using new repo address. User was removed because it's hardcoded in `nightwatch.json` anyway.
Maybe we need to configure new repo slug on saucelabs?

**Comment by goldylucks** [comment]
closing this, solved
