### ISSUE TITLE
Integrate coveralls.io

### ISSUE THREAD

**Issue by jacogr** [ethcore/eth-node-status-page#138]
Integrate coveralls.io (submission of coverage reports) -

1. Install relevant coveralls packages (see below)
2. create relevant coveralls commands
3. create coveralls token and encrypt as part of travis.yml
4. submit lcov.info to coveralls as part of CI build
5. integrate coveralls.io badge in README.md

Package install as copied from #136 (from memory)

- npm install --save-dev coveralls
- setup the COVERALLS_REPO_TOKEN environment variable
- run npm run testCoverage instead of npm run testOnce on npm run ci
- submit lcov.info via coveralls < coverage/lcov.info (as applicable npm run command)

**Comment by tomusdrw** [comment]
@jacogr Everything done here?

**Comment by jacogr** [comment]
Done. Can close.
