### ISSUE TITLE
Select for all "Address" fields

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/eth-node-status-page#33]
Instead of providing address user should be able to choose her account from a select box.

**Comment by Adam-Goldman7** [comment]
some users will prob'ly want an option for custom input
I think the simplest way to do it would b to use autocomplete

or we have a select box with a "custom" option, 
that turns the select to  text field

toughts?

**Comment by tomusdrw** [comment]
Autocomplete ftw.

**Comment by Adam-Goldman7** [comment]
hmm ...
it's inside an EditableValue component

u got any simple direction in mind?
