### ISSUE TITLE
Include new tracing API in RPC page

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/eth-node-status-page#61]
Include that: https://github.com/ethcore/parity/pull/997 in RPC select box
Docs: https://gist.github.com/debris/051c131e877affefeab4553509640a43

**Comment by Adam-Goldman7** [comment]
1. the methods name have no ethcore prefix, is that okay? I don't find the method in geth or rpc spec
(i.e "trace_filter")

2. the pr was made from this parity branch: tracedb_int
anything special needed to make it work?
or just compile as usual?

3. let's add the methods to the docs as well?

**Comment by tomusdrw** [comment]
1. The API is completely new - I spoke with @debris and decided to create separate namespace for that (because ethcore was already pretty big)
2. I guess compiling the branch should work fine.
3. Yup, definitely!
