### ISSUE TITLE
Auto-deployment of latest version

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/eth-node-status-page#62]
We should have a demo page with latest master version. Possibly using some existing node (parity node * or wrocity) or just using mocked values from test.utils.

Hosted on `gh-pages`.

**Comment by Adam-Goldman7** [comment]
is there a free node we can use?

would b cooler if it will actually work and people could play with it

**Comment by tomusdrw** [comment]
Yeah, we could use any of the `parity node pi/zero/one/beta` or `wrocity` or `icarus.parity.io`.
