### ISSUE TITLE
Disabling logger middleware in production

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/eth-node-status-page#65]

**Comment by Adam-Goldman7** [comment]
isn't useful?
in this case production might mean parity development right?

**Comment by tomusdrw** [comment]
Maybe there should be something to opt-out from logs? When you open a console you get a bunch of meaningless `[Object]` logs right now. You can also watch actions in `ReduxDevTools`.
I would got for some more descriptive logs (like `[ti:me:stamp] action: ActionType, payload: (object)`) or just remove them when we `npm run build` and bundle with parity.
